### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mruk** [DaMatrix/SaveSearcher#11]
Well, It's not unexpected. But do You plan to go to 9 or 11?
```
PS E:\Minecraft\tools> java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

PS E:\Minecraft\tools> java -jar .\SaveSearcher-1.6.2.jar --help
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.daporkchop.lib.common.util.PorkUtil (file:/E:/Minecraft/tools/SaveSearcher-1.6.2.jar) to method java.lang.Throwable.getOurStackTrace()
WARNING: Please consider reporting this to the maintainers of net.daporkchop.lib.common.util.PorkUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.daporkchop.savesearcher.Main.main(Main.java:94)
Caused by: java.lang.RuntimeException: Unable to find class: sun.misc.SoftCache
        at net.daporkchop.lib.common.util.PorkUtil.newSoftCache(PorkUtil.java:195)
        at net.daporkchop.lib.logging.impl.SimpleLogger.<init>(SimpleLogger.java:72)
        at net.daporkchop.lib.logging.impl.DefaultLogger.<init>(DefaultLogger.java:71)
        at net.daporkchop.lib.logging.Logging.<clinit>(Logging.java:35)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: sun.misc.SoftCache
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.daporkchop.lib.common.util.PorkUtil.newSoftCache(PorkUtil.java:192)
        ... 4 more
```

**Comment by DaMatrix** [comment]
i'm working on a rewrite of SaveSearcher, which will hopefully address this and some other issues. however, at the moment it only runs correctly on java 8.
