### ISSUE TITLE
cant start savesearcher-1.6.11.jar

### ISSUE THREAD

**Issue by ghost** [DaMatrix/SaveSearcher#16]
It says beginning scan of world and then gives me this error

[02/03/2022 20:35:02] [ALERT] ****************************************
[02/03/2022 20:35:02] [ALERT] * 
[02/03/2022 20:35:02] [ALERT] * java.lang.UnsupportedOperationException: create world
[02/03/2022 20:35:02] [ALERT] *     at net.daporkchop.lib.minecraft.world.format.anvil.AnvilSaveFormat.init(AnvilSaveFormat.java:82)
[02/03/2022 20:35:02] [ALERT] *     at net.daporkchop.lib.minecraft.world.impl.MinecraftSaveImpl.<init>(MinecraftSaveImpl.java:56)
[02/03/2022 20:35:02] [ALERT] *     at net.daporkchop.lib.minecraft.world.impl.SaveBuilder.build(SaveBuilder.java:48)
[02/03/2022 20:35:02] [ALERT] *     at net.daporkchop.savesearcher.Main.main(Main.java:243)
[02/03/2022 20:35:02] [ALERT] * 
[02/03/2022 20:35:02] [ALERT] ****************************************

**Comment by BasToTheMax** [comment]
i have this issue too!

**Comment by BasToTheMax** [comment]
How to fix it?
