### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by BasToTheMax** [DaMatrix/SaveSearcher#17]
My error:

```log
container@pterodactyl~ java -jar savesearcher.jar --input=world/ --output=result/ --dim=0 --block,id=minecraft:obsidian -o
[20/03/2022 10:26:18] [INFO] SaveSearcher v1.6.11
[20/03/2022 10:26:18] [INFO] Copyright (c) DaPorkchop_
[20/03/2022 10:26:18] [INFO] https://github.com/DaMatrix/SaveSearcher
[20/03/2022 10:26:18] [INFO] 
[20/03/2022 10:26:18] [INFO] Starting...
[20/03/2022 10:26:18] [WARN] Deleting contents of "/home/container/result" as -o is enabled...
[20/03/2022 10:26:18] [INFO] Beginning scan of world /home/container/world with 1 modules enabled.
[20/03/2022 10:26:18] [INFO] Modules:
[20/03/2022 10:26:18] [INFO]   Block (id=minecraft:obsidian)
[20/03/2022 10:26:19] [ALERT] ****************************************
[20/03/2022 10:26:19] [ALERT] * 
[20/03/2022 10:26:19] [ALERT] * java.lang.UnsupportedOperationException: save must be created by FML, otherwise we can't read the registry! (this feature will be added Soon(tm))
[20/03/2022 10:26:19] [ALERT] *     at net.daporkchop.lib.minecraft.world.format.anvil.AnvilSaveFormat.loadRegistries(AnvilSaveFormat.java:123)
[20/03/2022 10:26:19] [ALERT] *     at net.daporkchop.lib.minecraft.world.impl.MinecraftSaveImpl.<init>(MinecraftSaveImpl.java:60)
[20/03/2022 10:26:19] [ALERT] *     at net.daporkchop.lib.minecraft.world.impl.SaveBuilder.build(SaveBuilder.java:48)
[20/03/2022 10:26:19] [ALERT] *     at net.daporkchop.savesearcher.Main.main(Main.java:243)
[20/03/2022 10:26:19] [ALERT] * 
[20/03/2022 10:26:19] [ALERT] ****************************************
```

**Comment by BasToTheMax** [comment]
Do i need to open the world using Forge?

**Comment by thelampgod** [comment]
Yes or copy over a level.dat from another world that was created with forge (recommended).

**Comment by BasToTheMax** [comment]
Oke! I will try it, but copying the level.dat file of another world (opened with forge) will change the spawn location, right?

**Comment by thelampgod** [comment]
Yes but that doesn't matter for the program. You can do it temporarily and then copy back your original level.dat when the search is done.

**Comment by BasToTheMax** [comment]
I don't have access to my laptop at the moment. Maybe you can send a working `level.dat` file

**Comment by BasToTheMax** [comment]
It worked!
