### ISSUE TITLE
can't start the program

### ISSUE THREAD

**Issue by lomik31** [DaMatrix/SaveSearcher#20]
I get an error at startup:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.daporkchop.lib.logging.format.DefaultMessageFormatter.<init>(DefaultMessageFormatter.java:66)
	at net.daporkchop.lib.logging.impl.SimpleLogger.<init>(SimpleLogger.java:58)
	at net.daporkchop.lib.logging.impl.DefaultLogger.<init>(DefaultLogger.java:71)
	at net.daporkchop.lib.logging.Logging.<clinit>(Logging.java:35)
	at net.daporkchop.savesearcher.Main.main(Main.java:105)
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make private synchronized java.lang.StackTraceElement[] java.lang.Throwable.getOurStackTrace() accessible: module java.base does not "opens java.lang" to unnamed module @6ced7109
	at net.daporkchop.lib.common.util.PorkUtil.<clinit>(PorkUtil.java:92)
	... 5 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private synchronized java.lang.StackTraceElement[] java.lang.Throwable.getOurStackTrace() accessible: module java.base does not "opens java.lang" to unnamed module @6ced7109
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
	at net.daporkchop.lib.common.util.PorkUtil.<clinit>(PorkUtil.java:83)
	... 5 more
```

**Comment by NotStirred** [comment]
Try running with an older java version (8 should work fine)

Optionally you could instead add `--add-opens java.base/java.lang=ALL-UNNAMED` to your jvm args when running with a more recent java version

**Comment by lomik31** [comment]
If it helps someone: I used mac os and my program was on an external disk. So when copying the program, ._ files that for some reason tried to execute were created. There are two solutions for the problem:
1. Move the program to the disk apsf or hfs/hfs+
2. Run the command `dot_clean .` in the program directory
